#!/bin/bash
# OAuth 2.0 Server - curl Testing Examples
# A collection of curl commands to test all OAuth endpoints

BASE_URL="http://localhost:8000"
CLIENT_ID="client_replace_with_yours"
CLIENT_SECRET="secret_replace_with_yours"
AUTH_CODE="code_replace_with_code_from_authorize"
ACCESS_TOKEN="token_replace_with_access_token"
REFRESH_TOKEN="token_replace_with_refresh_token"

echo "╔════════════════════════════════════════════════════════╗"
echo "║  OAuth 2.0 Server - curl Command Examples             ║"
echo "║  Replace placeholders before running commands!         ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# 1. Get OAuth Server Info
echo "1️⃣  GET /oauth/info - OAuth Server Capabilities"
echo "────────────────────────────────────────────────"
echo ""
echo "curl $BASE_URL/oauth/info | jq"
echo ""
echo ""

# 2. User Registration
echo "2️⃣  POST /register - Create User Account"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -X POST $BASE_URL/register \\"
echo "  -d 'username=testuser' \\"
echo "  -d 'password=testpass123'"
echo ""
echo ""

# 3. User Login
echo "3️⃣  POST /login - Login User"
echo "────────────────────────────────────────────────"
echo ""
echo "# Store cookies in jar for session:"
echo "curl -c cookies.txt -b cookies.txt -X POST $BASE_URL/login \\"
echo "  -d 'username=testuser' \\"
echo "  -d 'password=testpass123'"
echo ""
echo ""

# 4. OAuth Info
echo "4️⃣  GET /oauth/info - Get OAuth Endpoints"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -s $BASE_URL/oauth/info | jq '.'"
echo ""
echo ""

# 5. Register OAuth Client
echo "5️⃣  POST /admin/clients - Register OAuth Client"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -c cookies.txt -b cookies.txt -X POST $BASE_URL/admin/clients \\"
echo "  -d 'app_name=My+Test+App' \\"
echo "  -d 'redirect_uris=http://localhost:3000/callback'"
echo ""
echo ""

# 6. Authorization Request
echo "6️⃣  GET /oauth/authorize - Request Authorization"
echo "────────────────────────────────────────────────"
echo ""
echo "# Open in browser or curl with session:"
echo "curl -b cookies.txt -L '$BASE_URL/oauth/authorize?client_id=$CLIENT_ID&redirect_uri=http://localhost:3000/callback&scope=profile+email&state=test123'"
echo ""
echo ""

# 7. Approve Authorization
echo "7️⃣  POST /oauth/authorize - Approve Authorization"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -c cookies.txt -b cookies.txt -X POST $BASE_URL/oauth/authorize \\"
echo "  -L"
echo ""
echo ""

# 8. Exchange Code for Tokens
echo "8️⃣  POST /oauth/token - Exchange Code for Tokens (Authorization Code Flow)"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -X POST $BASE_URL/oauth/token \\"
echo "  -d 'grant_type=authorization_code' \\"
echo "  -d 'code=$AUTH_CODE' \\"
echo "  -d 'client_id=$CLIENT_ID' \\"
echo "  -d 'client_secret=$CLIENT_SECRET' \\"
echo "  -d 'redirect_uri=http://localhost:3000/callback' | jq"
echo ""
echo ""

# 9. Get User Info
echo "9️⃣  GET /oauth/userinfo - Get User Information"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -s -H 'Authorization: Bearer $ACCESS_TOKEN' \\"
echo "  $BASE_URL/oauth/userinfo | jq"
echo ""
echo ""

# 10. Refresh Access Token
echo "🔟  POST /oauth/token - Refresh Access Token (Refresh Token Flow)"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -X POST $BASE_URL/oauth/token \\"
echo "  -d 'grant_type=refresh_token' \\"
echo "  -d 'refresh_token=$REFRESH_TOKEN' \\"
echo "  -d 'client_id=$CLIENT_ID' \\"
echo "  -d 'client_secret=$CLIENT_SECRET' | jq"
echo ""
echo ""

# 11. Test Invalid Token
echo "1️⃣1️⃣  GET /oauth/userinfo - Test Invalid Token"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -s -H 'Authorization: Bearer invalid_token' \\"
echo "  $BASE_URL/oauth/userinfo | jq"
echo ""
echo ""

# 12. Logout
echo "1️⃣2️⃣  GET /logout - Logout"
echo "────────────────────────────────────────────────"
echo ""
echo "curl -b cookies.txt $BASE_URL/logout"
echo ""
echo ""

# Full Automated Test
echo ""
echo "═══════════════════════════════════════════════════════"
echo "🚀 FULL AUTOMATED OAUTH FLOW TEST"
echo "═══════════════════════════════════════════════════════"
echo ""
echo "#!/bin/bash"
echo "# This script performs a complete OAuth flow"
echo ""
echo "BASE_URL=\"$BASE_URL\""
echo "COOKIES=\"cookies.txt\""
echo ""
echo "# 1. Create user account"
echo "echo 'Creating user account...'"
echo "curl -s -c \$COOKIES -X POST \$BASE_URL/register \\"
echo "  -d 'username=test' -d 'password=test' > /dev/null"
echo ""
echo "# 2. Login"
echo "echo 'Logging in...'"
echo "curl -s -c \$COOKIES -b \$COOKIES -X POST \$BASE_URL/login \\"
echo "  -d 'username=test' -d 'password=test' > /dev/null"
echo ""
echo "# 3. Register OAuth client"
echo "echo 'Registering OAuth client...'"
echo "curl -s -c \$COOKIES -b \$COOKIES -X POST \$BASE_URL/admin/clients \\"
echo "  -d 'app_name=TestApp' \\"
echo "  -d 'redirect_uris=http://localhost:3000/callback' | grep -o 'client_[a-f0-9]*' | head -1"
echo ""
echo "# 4. Request authorization"
echo "echo 'Requesting authorization...'"
echo "curl -s -b \$COOKIES -L \\"
echo "  '\$BASE_URL/oauth/authorize?client_id=CLIENT_ID&redirect_uri=http://localhost:3000/callback&state=test' > /dev/null"
echo ""
echo "# 5. Approve authorization (POST)"
echo "echo 'Approving authorization...'"
echo "curl -s -c \$COOKIES -b \$COOKIES -X POST \$BASE_URL/oauth/authorize | grep -o 'code=[^&]*'"
echo ""
echo "# 6. Exchange code for tokens"
echo "echo 'Exchanging code for tokens...'"
echo "curl -s -X POST \$BASE_URL/oauth/token \\"
echo "  -d 'grant_type=authorization_code' \\"
echo "  -d 'code=AUTH_CODE' \\"
echo "  -d 'client_id=CLIENT_ID' \\"
echo "  -d 'client_secret=CLIENT_SECRET' \\"
echo "  -d 'redirect_uri=http://localhost:3000/callback' | jq '.access_token'"
echo ""
echo "# 7. Get user info"
echo "echo 'Getting user information...'"
echo "curl -s -H 'Authorization: Bearer ACCESS_TOKEN' \\"
echo "  \$BASE_URL/oauth/userinfo | jq"
echo ""
echo ""

echo "════════════════════════════════════════════════════════"
echo ""
echo "💡 TIPS:"
echo "  • Use 'jq' for JSON formatting: pipe to '| jq'"
echo "  • Save cookies with '-c cookies.txt -b cookies.txt'"
echo "  • Test invalid tokens to verify validation"
echo "  • Replace all placeholder values before running"
echo ""
